### ISSUE TITLE
Support for Swift 4 and Xcode 9

### ISSUE THREAD

**Issue by JoshAtPCI** [kawoou/FlexibleImage#5]
Please add support for swift 4 and Xcode 9.
When building using swift 4 several build errors are returned.

`/Users/.../Pods/FlexibleImage/Sources/Filter/AddFilter.swift:49:32: 'setBuffer(_:offset:at:)' has been renamed to 'setBuffer(_:offset:index:)'
/Users/.../Pods/Metal.MTLComputeCommandEncoder:42:17: 'setBuffer(_:offset:at:)' was obsoleted in Swift 4
/Users/.../Pods/FlexibleImage/Sources/Filter/BlurFilter.swift:89:17: Value of optional type 'MTLTexture?' not unwrapped; did you mean to use '!' or '?'?
/Users/.../Pods/FlexibleImage/Sources/Filter/BlurFilter.swift:125:36: 'setTexture(_:at:)' has been renamed to 'setTexture(_:index:)'
/Users/.../Pods/Metal.MTLComputeCommandEncoder:90:17: 'setTexture(_:at:)' was obsoleted in Swift 4
/Users/.../Pods/FlexibleImage/Sources/Filter/BlurFilter.swift:128:36: 'setTexture(_:at:)' has been renamed to 'setTexture(_:index:)'
/Users/.../Pods/Metal.MTLComputeCommandEncoder:90:17: 'setTexture(_:at:)' was obsoleted in Swift 4
/Users/.../Pods/FlexibleImage/Sources/Filter/BlurFilter.swift:147:36: 'setBuffer(_:offset:at:)' has been renamed to 'setBuffer(_:offset:index:)'
/Users/.../Pods/Metal.MTLComputeCommandEncoder:42:17: 'setBuffer(_:offset:at:)' was obsoleted in Swift 4`

Thanks

**Comment by JoshAtPCI** [comment]
Version 1.8 fixes the comparability issues with Xcode 9 and Swift 4. At this time it does not look like cocoapods has updated yet.  Anyone wanting to use version 1.8 before cocoapods updates can use the following line in their pod file.

`pod 'FlexibleImage', git: => 'https://github.com/kawoou/FlexibleImage.git'`

**Comment by kawoou** [comment]
Sorry. Has confirmed.
I omit the cocoapods update. I will process it immediately.

Thanks

**Comment by JoshAtPCI** [comment]
I can confirm that cocoapods now has version 1.8.
Thanks
